### ISSUE TITLE
[Feature request] Reminders

### ISSUE THREAD

**Issue by kristijanhusak** [unfog-io/unfog-vim#12]
Hi,

do you maybe plan to introduce reminders?

For example, if i set due date in 1 hour, I would like to get notified somehow (a floating window or something) like 5 or 10 min before the task that it is being due in 5/10 min. This would of course work only for vim 8 and neovim that have `timers` feature.
Idea is to set up a timer that checks every minute if there is anything due in [given time], and present it to the user.

This is more of a "Todo manager" thing, but I think it would be neat to have it.
I can help on the vim side, but i'm not really familiar with Haskell.

**Comment by soywod** [comment]
Thanks for your feedback. Indeed, it sounds like an interesting feature. However I don't think it should be implemented Vim plugin side. First because this plugin should not contain any logic (it used to be the case, but I'm fighting against, I prefer this plugin to remain a vue), and also because it requires Vim to be started and running to have notifications. I move the discussion [here](https://github.com/soywod/unfog/issues/41).
