### ISSUE TITLE
weird interaction with certain keymappings

### ISSUE THREAD

**Issue by norseghost** [unfog-io/unfog-vim#7]
I am having trouble using `<leader>` keymaps within unfog. 

It kinda seems like unfog is swallowing my leader key.

Example:
`<leader>sc` is 'session close'. instead, I delete character under cursor, and insert a `c`

**Comment by soywod** [comment]
It looks like `<leader>` mappings are lost in local buffers. Personally I use `<ctrl>` and `<alt>`, and it seems to keep all of them. I just tried with a `<leader>` mapping and I reproduce your issue. I will investigate :mag:

**Comment by soywod** [comment]
Is your `<leader> = space` by any chance? Space is used to refresh the list by default, and conflicts with your leader (I reproduced the case). I will remove this mapping, since you can refresh by recalling `:Unfog`. Meanwhile your can disable the refresh mapping with `nmap NONE <plug>(unfog-list)`, and it should work.

**Comment by norseghost** [comment]
indeed, my leader = space!
